pipeline {
    agent {
        label "abdullah"
    }

    triggers {
        githubPush()
    }

    stages {

        stage("Code") {
            steps {
                echo "Cloning code..."
                git branch: 'main',
                    url: 'https://github.com/abdullahensari44-a11y/django-notes-app.git'
            }
        }

        stage("Build") {
            steps {
                echo "Building Docker image..."
                sh 'docker build -t notes-app:latest .'
            }
        }

        stage("Push to DockerHub") {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerHub',
                    usernameVariable: 'dockerHubUser',
                    passwordVariable: 'dockerHubPass'
                )]) {

                    sh '''
                    docker login -u $dockerHubUser -p $dockerHubPass
                    docker tag notes-app:latest $dockerHubUser/notes-app:latest
                    docker push $dockerHubUser/notes-app:latest
                    '''
                }
            }
        }

        stage("Deploy") {
            steps {
                sh '''
                docker rm -f notes-app-container || true

                docker run -d \
                  --name notes-app-container \
                  --env-file .env \
                  -p 8000:8000 \
                  notes-app:latest
                '''
            }
        }
    }
}
